name: Surf & Tide Data Automation

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC (8am EDT)

jobs:
  fetch-surf-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Fetch NOAA tide data and save CSV
        run: |
          import datetime
          import requests

          today = datetime.datetime.utcnow().strftime('%Y%m%d')
          tomorrow = (datetime.datetime.utcnow() + datetime.timedelta(days=1)).strftime('%Y%m%d')

          url = f"https://tidesandcurrents.noaa.gov/api/datagetter?product=predictions&application=NOS.COOPS.TAC.WL&begin_date={today}&end_date={tomorrow}&datum=MLLW&station=8419318&time_zone=lst_ldt&units=english&interval=hilo&format=csv"
          response = requests.get(url)

          with open("noaa_tides.csv", "w") as f:
              f.write(response.text)

      - name: Upload tide data CSV
        uses: actions/upload-artifact@v4
        with:
          name: noaa-tide-data
          path: noaa_tides_
